import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import Image from "next/image"



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.home}>Home Page</h1>
        <Link className={styles.useEffect1} href='/useEffectOne'>useEffectOne</Link>
        <Link className={styles.useEffect2} href="/useEffectTwo">useEffectTwo</Link>
        <Link className={styles.useEffect3} href="/useEffectThree">useEffectThree</Link>
        <Link className={styles.carousel} href="/carouselPage">CarouselPage</Link>

        <Image className={styles.gradHat}
                    src={"/icons/graduation-hat.png"}
                    alt={"/icons/graduation-hat.png"}
                    width={50}
                    height={50}
                />

                <Image className={styles.menuBar}
                    src={"/icons/menu-icon.png"}
                    alt={"/icons/menu-icon.png"}
                    width={50}
                    height={40}
                />
      
      </main>
    </>
  )
}
